os:
  - linux
  - osx
language: java
jdk:
  - openjdk10
  - openjdk11
env:
  - WORKDIR=singleton
  - WORKDIR=objectpool
  - WORKDIR=factorymethod
  - WORKDIR=bridge
  - WORKDIR=composite
  - WORKDIR=memento
before_script:
  - cd $WORKDIR
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
