os:
  - linux
  - osx
language: java
jdk:
  - openjdk10
  - openjdk11
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
      os_image: xcode10
    - os: osx
      os_image: xcode11
env:
  - WORKDIR=singleton
  - WORKDIR=objectpool
before_script:
  - cd $WORKDIR
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
